### ISSUE TITLE
Newer packages not listed in packages.json

### ISSUE THREAD

**Issue by Xilonz** [cedaro/satispress#110]
After updating some of the plugins and themes, I wasn't able to update using composer. It turns out that my packages.json only lists the oldest version (or initially installed version) available. The backend (satispress -> packages tab) correctly shows all available packages. 

This isn't caused by any caching issue, because if I install a new plugin or theme it correctly shows in in de packages.json.

**Comment by bradyvercher** [comment]
The Packages tab and packages.json both use the same code to list the versions, so that's strange that they'd show in one place and not the other. If they're showing on the Packages tab, then the cached released must exist in the `wp-content/uploads/satispress-***/packages` directory. I'd verify that those files exist and you can download them from the Packages tab first.

Otherwise, you might check to see if it's a permissions issue. The releases that show in the `packages.json` output are [transformed and filtered here](https://github.com/cedaro/satispress/blob/a9d5f353d33bef837227a7a49882abd84be08d80/src/Transformer/ComposerRepositoryTransformer.php#L89-L103).

**Comment by Xilonz** [comment]
Hi, I'm not sure what went wrong and I can't reproduce it. It all seems to function now.

**Comment by bradyvercher** [comment]
Glad to hear everything is working and thanks for following up on this!

**Comment by jeff-becker-projekt202** [comment]
I just experienced this issue as well. Specifically a new version of a theme was not published out to packages.json until I made additional themes available and clicked 'Save Changes'. Once I did that, the new theme versions were visible in packages.json
