### ISSUE TITLE
Plugins are downloaded even if automatic updates are disabled

### ISSUE THREAD

**Issue by Striffly** [cedaro/satispress#181]
Hello

I notice that the last versions of the plugin are downloaded even if the automatic updates are disabled. This is a problem especially to lock some plugins to specific versions (example with Formidable & Formidable Pro, whose versions differ because of automatic updates that are not synchronized between these two plugins).
Is it possible to take this parameter into account when retrieving the available versions (example: no version higher than the current version of the plugin)?

Thanks !

**Comment by bradyvercher** [comment]
Hi @Striffly, that's the expected behavior. The version WordPress is running doesn't get modified, but SatisPress does save the most recent version so that they can be made available to Composer. You should be specifying the exact version in `composer.json` to prevent updates if that's the behavior you want.

Let me know if I've misunderstood you or you have any other questions about how this works.
