### ISSUE TITLE
The future of this, maintained?

### ISSUE THREAD

**Issue by kimmenbert** [cedaro/satispress#212]
Hi, thanks for making this awesome thing! No big issues to report. I just wanted to do a health check on this. Is this project active, or are people using something else these days?

**Comment by thefrosty** [comment]
I haven't seen a lot of activity on here. I have a forked version that supports PHP >= 8.1 tagged: https://github.com/thefrosty/satispress/releases/tag/2.0.0

**Comment by andronocean** [comment]
@thefrosty Thank you for this — just made my day! I was trying to get SatisPress on a PHP 8.2 site that was using `composer/installers` at 2.2. Thought I was in for a world of pain till I saw your comment.

**Comment by lvinceslas** [comment]
@thefrosty Thank you for this upgrade but I can't install it using composer : `composer install thefrosty/satispress`. Is there a way to do it ?

**Comment by tyrann0us** [comment]
Hi @bradyvercher, can you say something about the future of this project? Thank you so much!

**Comment by bradyvercher** [comment]
@tyrann0us The project I built SatisPress for is currently using it without any issues, so I've considered it to be pretty stable. I realize there are maintenance tasks that need to be addressed that I haven't had time to look into. I'm certainly open to contributions or bringing on a contributor from a team that depends on SatisPress.

**Comment by tyrann0us** [comment]
Hi @bradyvercher, thank you for getting back to me!
I commented because some PRs, like #188 or #210, have been waiting to be reviewed and ideally merged for quite some time already. Also, some changes on `develop` have also been sitting unreleased for quite some time (https://github.com/cedaro/satispress/compare/v1.0.4...develop).
>I'm certainly open to contributions or bringing on a contributor from a team that depends on SatisPress.

While I can't make any promises, the company I work for (https://github.com/inpsyde) uses SatisPress, and we might have the resources to contribute to the package. Therefore, feel free to add me as a contributor.
Thank you!

**Comment by bradyvercher** [comment]
I released an updated version of SatisPress that includes a number of updates and compatibility with the latest versions of PHP. Feel free to open any issues if you run into a problem.

@thefrosty If you don't want to maintain a fork, I can provide commit access if you'd like to address issues I'm not able to get to in a timely manner in the future.

**Comment by thefrosty** [comment]
Sure, that would be great 👍🏼

**Comment by kimmenbert** [comment]
Awesome! Thank you again for making this @bradyvercher
