### ISSUE TITLE
v0.3.0 Installing issue (Fatal error)

### ISSUE THREAD

**Issue by Nobiuss** [cedaro/satispress#76]
Hi Team, 

We have seen the update here on github so we removed the old version and installed this new one and had some errors. 

Plugin could not be activated because it triggered a fatal error. ----->

Fatal error: Uncaught LogicException: Function 'SatisPress\autoloader_classmap' not found (function 'SatisPress\autoloader_classmap' not found or invalid function name) in /home/*******/apps/plugins/wp-content/plugins/satispress/satispress.php:48 Stack trace: #0 /home/*******/apps/plugins/wp-content/plugins/satispress/satispress.php(48): spl_autoload_register('SatisPress\\auto...') #1 /home/*******/apps/plugins/wp-admin/includes/plugin.php(1897): include('/home/*******...') #2 /home/*******/apps/plugins/wp-admin/plugins.php(178): plugin_sandbox_scrape('satispress/sati...') #3 {main} thrown in /home/*******/apps/plugins/wp-content/plugins/satispress/satispress.php on line 48

<----

Kind regards, 
Kim

**Comment by thefrosty** [comment]
It looks live version `0.3` requires the plugin to be installed via composer (composer install) _so the vendor directory is present_, as it's not including the functions.php file manually. Is the intended? I was hoping to run this plugin outside of my normal composer sites in some stand-alone installs I could download and upload the zip too.

**Comment by bradyvercher** [comment]
@thefrosty To upload a zip instead of using Composer, you need to [download the packaged release asset](https://github.com/cedaro/satispress/releases/download/v0.3.0/satispress-0.3.0.zip) that includes the vendor directory. It's available from the [releases page](https://github.com/cedaro/satispress/releases) and is the file named `satispress-{version}.zip`. I'm not sure if there's a better way to highlight that or not.

@Nobiuss Does using the release asset fix the error you're seeing?

**Comment by thefrosty** [comment]
That makes sense to me. I didn't try that, was just looking at the code.

**Comment by thefrosty** [comment]
Just testing again locally the way I imaging quite a few users my install this plugin; via the afragen/github-updater. Which installs the latest master branch. I would suggest adding the custom [release-assets](https://github.com/afragen/github-updater/wiki/Settings#release-assets) header so it knows to download `$repo-$tag.zip`

**Comment by thefrosty** [comment]
Thanks, I've asked that question: https://github.com/afragen/github-updater/issues/712

**Comment by GaryJones** [comment]
> I'm not sure if there's a better way to highlight that or not.

If someone is using Composer, then they should have the `vendor` directory. 

If someone is using the release zip, then they should have the vendor directory.

I think the only scenario when it might not exist, would be if they did a git clone, and forgot to run `composer install`. We could check if the `autoload_classmap()` function exists, and if not, `exit('Please run "composer install".')` as a reminder.

Maybe also add a comment just above, explaining about the release zip, so if anyone else was "just looking at the code", they'd be suitably informed.

**Comment by afragen** [comment]
@GaryJones it’s probably simpler to add a new feature to install via a URL if the user wants to use the GitHub Updater Install feature. The trick would be getting the user to use that one. It still a matter of getting the user to install in the correct manner, composer or the release asset.

https://github.com/afragen/github-updater/issues/713

**Comment by bradyvercher** [comment]
@GaryJones 
> I think the only scenario when it might not exist, would be if they did a `git clone`, and forgot to run `composer install`.

When downloading a WordPress plugin from GitHub, I think people might be conditioned to download the source zip on the releases page or from this popup, which wouldn't include the `vendor` directory, either:

<img width="564" alt="screen shot 2018-09-05 at 9 09 54 am" src="https://user-images.githubusercontent.com/1302030/45107650-1fae7780-b0ef-11e8-953a-605e87e734ef.png">

> We could check if the `autoload_classmap()` function exists, and if not, `wp_die('Please run <code>composer install</code>.')` as a reminder.

Checking for dependencies would work. Instead of exiting and preventing access to the site, we can probably display an admin notice with a link to the installation instructions.

**Comment by bradyvercher** [comment]
#76 should prevent fatal errors and direct users to the installation instructions if dependencies are missing. I'm pretty sure the original issue is related, so I'll close this out. @Nobiuss, feel free to reopen this if you're still having problems.

**Comment by Nobiuss** [comment]
Great work guys. I will test this later.

**Comment by afragen** [comment]
@GaryJones @Nobiuss @bradyvercher @thefrosty GitHub Updater develop branch now has the ability to install from a zipfile, remote URL or a local file. No directions as yet, I'm interested in knowing how easy it is to figure out.

**Comment by polevaultweb** [comment]
> If someone is using Composer, then they should have the vendor directory.

I came across this recently. I installed the plugin via Composer (whole site managed with composer.json) in the root.

And I see 
![image](https://user-images.githubusercontent.com/1770201/64457874-b9867700-d0eb-11e9-88bb-17742d3d5e3e.png)

Because the plugin is looking for the vendor directory in it's directory. This wont exist as the vendor dir is at the site root.

**Comment by bradyvercher** [comment]
Hi @polevaultweb! SatisPress doesn't check for a vendor directory. It checks to see if the `\SatisPress\autoloader_classmap()` function exists. [That function](https://github.com/cedaro/satispress/blob/a9d5f353d33bef837227a7a49882abd84be08d80/src/functions.php#L27-L42) is defined in `/src/functions.php` and should be [autoloaded by Composer](https://github.com/cedaro/satispress/blob/a9d5f353d33bef837227a7a49882abd84be08d80/composer.json#L68-L70), so if it doesn't exist, dependencies probably aren't available.

I run SatisPress on a site that's managed by Composer (SatisPress is installed by Composer) and haven't run into this issue.

If you open the `/vendor/composer/autoload_files.php` file, you should see an entry for `.../plugins/satispress/src/functions.php`. If that's missing, you might need to trying running `composer install` again or `composer dump-autoload` to see if it'll add that entry.

**Comment by polevaultweb** [comment]
Hmmm, i was referring to https://github.com/cedaro/satispress/blob/a9d5f353d33bef837227a7a49882abd84be08d80/satispress.php#L44 but of course that's for packaged up plugins. Weird why the composer autoloader isn't boostrapping the functions.php file - ill do some more digging. Apologies for the false alarm.
