### ISSUE TITLE
Plugins Aren't Available

### ISSUE THREAD

**Issue by cjkoepke** [cedaro/satispress#77]
When installing SatisPress on a brand new installation, themes will show up correctly once installed. Plugins, however, are not showing up on the configuration screen (I installed several), nor are they showing up on the packages tab.

Is there something I need to do to enable plugins?

**Comment by bradyvercher** [comment]
Plugins don't show on the settings screen like themes. Instead, they can be whitelisted on the _Plugins &rarr; Installed Plugins_ screen. The [docs have a screenshot](https://github.com/cedaro/satispress/blob/develop/docs/whitelisting.md) showing what it should look like, but let us know if that's not what you're seeing.

**Comment by cjkoepke** [comment]
@bradyvercher This worked, thanks. Any reason the plugin activation interface isn't grouped with the themes? Seems more intuitive — happy to make a pull request if that helps.

Thanks again!

**Comment by bradyvercher** [comment]
No particular reason at this point. After the core themes screen was redesigned way back when, there wasn't a hook to manage them like plugins, which is why they're on the settings screen instead.

Most of the UI was put together quickly to make the concept serviceable. The difference has caused confusion in the past, so I'd be fine with moving plugins to the settings screen as well if you want to take a look into that.
