### ISSUE TITLE
Only start logging when WP_DEBUG is true

### ISSUE THREAD

**Issue by koenHuybrechts** [cedaro/satispress#86]
At this moment, Monolog is used to log certain (fatal?) errors in Satispress.
But if one doesn't setup Monolog, the error fails and blocks Satispress from processing updates. Without any notification.

A solution cna be to implement an extra check if WP_DEBUG is enabled, so logging only happens when the website owner wants logging to happen.

**Comment by marcus-hiles** [comment]
👍 thanks for this

**Comment by bradyvercher** [comment]
SatisPress uses a [null logger](https://github.com/cedaro/satispress/blob/3ff7ffe56f32b9b744dff0fba23b2fc0beff4d76/src/ServiceProvider.php#L169-L171) that implements the PSR-3 Logger interface so a custom logger that implements the same interface can be used. It doesn't actually write anywhere by default and it shouldn't swallow fatal errors -- those should still be handled by WordPress and respect the `WP_DEBUG` settings.

Monolog isn't actually used directly or even required if you want to log SatisPress messages. The [logging docs](https://github.com/cedaro/satispress/blob/develop/docs/logging.md) demonstrate how to implement a logger using Monolog because it's widely used, makes for a concise example, and has a lot of handlers and formatters.

Some of the [information SatisPress logs](https://github.com/cedaro/satispress/search?q=logger-%3E&unscoped_q=logger-%3E) would probably just pollute `debug.log` since it's mostly useful for development, debugging, or monitoring, but replacing the `NullLogger` with a basic implementation that writes errors to `debug.log` when `WP_DEBUG` is enabled should be feasible.

**Comment by bradyvercher** [comment]
@koenHuybrechts Let me know if you have any feedback about the latest iteration on the logger. It should log warnings and higher when `WP_DEBUG` is enabled.
